### ISSUE TITLE
Automating the nginx/ssl

### ISSUE THREAD

**Issue by telent** [ummjackson/mastodon-guide#1]
I like this guide very much. When I went through the same process the other day, I also built nginx as a container with  semiautomatic letsencrypt support - you can have a look at http://guthub.com/telent/letsencruft

**Comment by telent** [comment]
damn, pressed Send accidentally
..

https://github.com/telent/letsencruft and see if you think it makes the instructions simple to incorporate that

**Comment by ummjackson** [comment]
Nice! Part of me likes having the nginx proxy run outside a container, but I can see why it'd be nice to have it setup like this. I'll write up auto-renewal as per the current guide first, then perhaps offer this as an alternative?

**Comment by ummjackson** [comment]
Added the section with a regular cron job setup for Let's Encrypt. Will leave it this way for now as I don't want to confuse people by bringing another container into the mix.
