### ISSUE TITLE
sudo apt-cache policy docker-engine issue on Ubuntu Xenial

### ISSUE THREAD

**Issue by zbam** [ummjackson/mastodon-guide#2]
Hi, How did you deal with this issue ?
```
mastodon@xxxxxxxx:~$ sudo apt-cache policy docker-engine
N: Unable to locate package docker-engine
```
It is a known issue that has not been solved yet (from what I understand)
see https://forums.docker.com/t/problem-installing-docker-on-ubuntu-xenial-16-04/9273 and https://github.com/docker/docker/pull/21461#issuecomment-205303292

**Comment by ummjackson** [comment]
Hmm, I'm unable to reproduce the issue and I believe that Docker issue was closed... Can you try re-running all of the commands in the ["Install Docker"](https://github.com/ummjackson/mastodon-guide/blob/master/up-and-running.md#install-docker) section again, as the root user?

**Comment by ummjackson** [comment]
Closing as no response, please re-open an issue if you can reproduce this.
