### ISSUE TITLE
This says Digital Ocean,

### ISSUE THREAD

**Issue by LWFlouisa** [ummjackson/mastodon-guide#30]
But I've used things like Localtunnel that routes through a localhost server. Wouldn't it be better to do that, or maybe some way to host it over IPFS?

I hear about IPNS all the time, but it didn't exactly suit my purpose my my portfolio blog, which hosts the Jekyll generated blog just fine, as long as I create snapshot of the local hosted site, and upload that to IPFS.

There is Beaker, which is suppose to be serverless, but having difficulties with it.

**Comment by ummjackson** [comment]
Mastodon needs to live on a server that sits somewhere. IPFS, Beaker/Dat etc. are entirely different protocols.
