### ISSUE TITLE
chown error

### ISSUE THREAD

**Issue by snowe2010** [ummjackson/mastodon-guide#32]
I'm not sure why this happened, but I followed all steps exactly, but then received this error during the docker-compose build. 

```
Step 29/37 : COPY --chown=mastodon:mastodon . /opt/mastodon
ERROR: Service 'web' failed to build: Unknown flag: chown
```

Not sure what other info to provide, as the log is a zillion lines long.

**Comment by snowe2010** [comment]
[Apparently this is caused by the version being lower than 17.09](https://github.com/moby/moby/issues/35731#issuecomment-364346334). The instructions specify to install docker-engine, which is the old version. By uninstalling `docker-engine` and following the install instructions at https://docs.docker.com/v17.09/engine/installation/linux/docker-ce/ubuntu/#install-docker-ce-1 I got the entire build to succeed, which 99.999999% less red text than before. 

I think the instructions need to be updated to install the correct docker version.

**Comment by ummjackson** [comment]
Thanks, just merged your PR. https://github.com/ummjackson/mastodon-guide/commit/1c8f17f199e6aed19c27b7c21009491fb24a1068
