### ISSUE TITLE
Public Key Clarification in docs

### ISSUE THREAD

**Issue by jwithington** [ummjackson/mastodon-guide#4]
Hey hey! Awooooo from @jwithy@xoxo.zone !

The very beginning of the guide over at up-and-running.md states in line 25

>If you'd like to setup public key authentication, now is the time to do so... it's recommended and Google is your friend for finding an easy guide.

This comes across as a bit vague to me -- are you talking about seeing up public key authentication for all/future users, or for the new `su - mastodon` user? I think you meant just for the first user, but wanted to make sure. 

Depending on what you mean, I'd be more than happy to submit a PR to add some clarity/resources to the docs. Thanks so much for this guide! Awooo!

**Comment by ummjackson** [comment]
@jwithington - glad you found the guide helpful!! I'm just referring to the new `mastodon` user we just created... one would hope that the `root` account is already being accessed via key and not password (although I didn't want to go into that in the article as it's not required for the install). 

Would happily accept a PR clarifying this is for the `mastodon` user, and even a hyperlink out to a respectable site outlining the process.

**Comment by ummjackson** [comment]
Actually... thinking harder on this one: should we perhaps drop that paragraph altogether? Ideally the `mastodon` user should only be accessible via `su - mastodon` and not via external/remote SSH login. Thoughts/opinions appreciated!!

**Comment by jwithington** [comment]
Well, I'm not experienced enough with that sorta thing to weigh in -- and haven't even set up an instance yet! -- but it's possible that (unless it's out of scope for this) we could just include a bit about both sides of it.

**Comment by ummjackson** [comment]
Removed this piece as it's kinda confusing and I'll let admins decide how they go about securing their users themselves. 😁
