### ISSUE TITLE
nginx restart fails

### ISSUE THREAD

**Issue by jasonkgreen** [ummjackson/mastodon-guide#5]
Following guide.  Thanks for all the work on this , by th3e way. When I try to restart nginx I get an error. No idea how to proceed.

**Comment by ummjackson** [comment]
Thanks, glad the guide is helping people. 

Regarding nginx issues, you'll usually hit these if your site config has something broken in it... please review the file you created in /etc/nginx/sites-available and make sure there are no errors. 

First, to check that the nginx config itself is fine run:

`sudo nginx -t`

If that all looks good but you still can't restart, try looking at the error log:

`sudo tail /var/log/nginx/error.log`

If there are config errors in your site definition, they should show up there.

**Comment by ummjackson** [comment]
Saw the reply on Mastodon itself that you got this work, it was just a stray `}`

All the best! 👍
