### ISSUE TITLE
Docker install suggestion

### ISSUE THREAD

**Issue by jrimmer** [ummjackson/mastodon-guide#7]
Followed your doc to setup an instance - thanks for the fine, and comprehensive, work!

From a vanilla Ubuntu 16.04, via Scaleway, I needed to do the following to install Docker - supporting HTTPS apt endpoints and adding the apt-add-repository binary:

```
$ sudo apt-get install apt-transport-https software-properties-common
```

I'm happy to provide a pull-request if you'd prefer.

**Comment by ummjackson** [comment]
Ahh, interesting catch. Would happily accept a PR! 👍

**Comment by jrimmer** [comment]
Will do!
