### ISSUE TITLE
Suggestion for 'Email confirmation isn't working' section

### ISSUE THREAD

**Issue by jrimmer** [ummjackson/mastodon-guide#8]
In completing the setup work I encountered an issue where email wasn't being sent - the host I'm using, Scaleway, blocks the *standard* SMTP ports. For Mailgun (and Sparkpost supports this) I used port 2525 instead and everything worked well.

**TroubleShooting Section Suggestion**
1. Add changing SMTP port to 2525 should email send failure occur.
1. Add mention of Docker commands to see container logs, such as: ``docker logs mastodon_web_1``

Happy to create a pull request if you'd prefer.

**Comment by ummjackson** [comment]
Wow, email is proving to be such a hassle for people - hard to troubleshoot too! Happy to review/accept a PR. 👍

**Comment by jrimmer** [comment]
Will do!
